#!/usr/bin/env bash
# =============================================================================
# export_abis.sh
# NFT Airdrop Platform — P1-I8
#
# Exports the ABI for every platform contract into frontend/src/abis/
# so Phase 2 (React dApp) can import them directly.
#
# Usage:
#   bash script/export_abis.sh
#
# Prerequisites:
#   forge build must pass before running this script.
#
# What it does:
#   1. forge inspect <Contract> abi  → outputs raw ABI JSON
#   2. Writes each ABI to frontend/src/abis/<Contract>.json
#   3. Generates an index file that re-exports all ABIs as named exports
# =============================================================================

set -e  # exit on any error

# ── Colours ───────────────────────────────────────────────────────────────────
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Colour

# ── Config ────────────────────────────────────────────────────────────────────
ABI_DIR="frontend/src/abis"
mkdir -p "$ABI_DIR"

echo -e "${YELLOW}Building contracts first...${NC}"
forge build --silent
echo -e "${GREEN}Build successful.${NC}\n"

# ── Export each contract ABI ──────────────────────────────────────────────────
declare -A CONTRACTS=(
    ["NFT721"]="src/tokens/NFT721.sol:NFT721"
    ["NFT1155"]="src/tokens/NFT1155.sol:NFT1155"
    ["AirdropController"]="src/airdrop/AirdropController.sol:AirdropController"
    ["MerkleAirdrop"]="src/airdrop/MerkleAirdrop.sol:MerkleAirdrop"
    ["AdminGuard"]="src/governance/AdminGuard.sol:AdminGuard"
    ["AirdropScheduler"]="src/airdrop/AirdropScheduler.sol:AirdropScheduler"
)

echo "Exporting ABIs to $ABI_DIR/"
echo "─────────────────────────────────────────"

for NAME in "${!CONTRACTS[@]}"; do
    SELECTOR="${CONTRACTS[$NAME]}"
    OUTPUT="$ABI_DIR/${NAME}.json"

    forge inspect "$SELECTOR" abi > "$OUTPUT"

    # Count exported functions for the summary
    FUNC_COUNT=$(cat "$OUTPUT" | grep -c '"type":"function"' || echo "?")

    echo -e "  ${GREEN}✓${NC} ${NAME}.json  (${FUNC_COUNT} functions)"
done

echo ""

# ── Generate TypeScript index file ───────────────────────────────────────────
INDEX_FILE="$ABI_DIR/index.ts"

cat > "$INDEX_FILE" << 'TYPESCRIPT'
/**
 * ABI Exports — NFT Airdrop Platform
 * Auto-generated by script/export_abis.sh — do not edit manually.
 * Re-run: bash script/export_abis.sh
 */

export { default as NFT721ABI }            from './NFT721.json'
export { default as NFT1155ABI }           from './NFT1155.json'
export { default as AirdropControllerABI } from './AirdropController.json'
export { default as MerkleAirdropABI }     from './MerkleAirdrop.json'
export { default as AdminGuardABI }        from './AdminGuard.json'
export { default as AirdropSchedulerABI }  from './AirdropScheduler.json'
TYPESCRIPT

echo -e "${GREEN}✓${NC} index.ts generated"
echo ""

# ── Done ──────────────────────────────────────────────────────────────────────
echo -e "${GREEN}All ABIs exported successfully to ${ABI_DIR}/${NC}"
echo ""
echo "Usage in Phase 2 React components:"
echo "  import { NFT721ABI, AirdropControllerABI } from '@/abis'"
echo ""
echo "Next steps:"
echo "  forge script script/VerifyAll.s.sol --rpc-url \$RPC_URL_SEPOLIA -vvvv"
